### ISSUE TITLE
2 Problem

### ISSUE THREAD

**Issue by OscarNaslundCuesta** [Daky60/provbokning_trafikverket#1]
Första problemet lyckades jag lösa med hjälp av en polare.
På rad 87 behöver det vara 'id-control-searchText-1-1' och inte 'id-control-searchText'

Däremot har jag testat att köra skripten på en tid i Uppsala som jag inte är intresserad av men som är ledig. Då har hela skiten "kraschat" efter att ha hittat den lediga tiden. Chrome stängs alltså ned och inget ljud spelas upp och jag ser inte att någon uppkörning är förbokad. Vad beror detta på?

Mvh Oscar

**Comment by Knaspersky** [comment]
Tack för den första lösningen.

**Comment by Knaspersky** [comment]
När jag körde skripten utan 'id-control-searchText-1-1' så kollade den bara i Stockholm City och då fick jag en tid men den sa att den tiden inte var tillgänglig längre. Vet du något om det?

**Comment by OscarNaslundCuesta** [comment]
Stockholm City har också kommit upp för mig tidigare, men det finns inte ens något sådant ställe för uppkörning (?). Nu får jag inte upp det längre. För mig funkar endast skripten om jag kör "-1-1" på slutet, annars blir det någon random location. Däremot har jag fortfarande problem när jag väl hittar en tid.

**Comment by Knaspersky** [comment]
Jag kollar dock efter AM teoriprov

**Comment by Knaspersky** [comment]
Bör man logga in snabbt innan den refreshar?

**Comment by OscarNaslundCuesta** [comment]
Nej det tror jag inte. Problemet för mig är bara att chrome stängs ned utan ljud eller förbokning (tror jag)

**Comment by Knaspersky** [comment]
För mig så stängs inte chrome ner utan det kommer upp en ruta längst ner i vänstra hörnet som säger att tiden inte längre är tillgänglig.

**Comment by Knaspersky** [comment]
Kör du med rätt chromedriver?

**Comment by OscarNaslundCuesta** [comment]
Ja, 89.0.4389.114 och 89.0.4389.23 borde väl räknas som samma.

Spelas ljudet för dig då?

**Comment by Knaspersky** [comment]
För mig så spelas ljudet. Men första gången jag körde den så stod det i CMD att jag använde fel chromedriver sen sa den vilken jag skulle använda.

**Comment by Knaspersky** [comment]
chrome://settings/help. Där står det också vilken chrome du har.

**Comment by Knaspersky** [comment]
Allting verkar fungera nu. Jag hittade en tid om 7 dagar som jag kunde resarvera men bara för att kolla om det fungerade nu.

**Comment by Knaspersky** [comment]
Jag kör med 89.0.4389.23.

Men stänger chrome bara ner när du får en ledig tid? Eller är det när du får den lediga tiden i uppsala?

**Comment by Knaspersky** [comment]
Nu fick jag en tid

**Comment by Knaspersky** [comment]
Jag tror du borde logga in.

**Comment by OscarNaslundCuesta** [comment]
Logga in med personnummer gör jag redan. Menar du med BankID också?

**Comment by Knaspersky** [comment]
Ja, jag menar att du ska logga in här
![2021-04-07 (5)_LI](https://user-images.githubusercontent.com/53581552/113904596-82e67600-97d2-11eb-8dc2-fe1b6d009f0f.jpg)

**Comment by Knaspersky** [comment]
Så när den håller på och letar efter tider så klickar du på logga in precis efter sidan har refreshat där du skriver in ditt personnummer (snabbast om du gör det med CTRL + V), sedan verifierar du dig med BankID (du bör använda fingeravtryck för att hinna innan sidan refreshar).

**Comment by OscarNaslundCuesta** [comment]
Ok, fattar nu. Behöver man fortfarande confirma tidsbokningen inom 15 min eller gör den det automatiskt tror du?

**Comment by Knaspersky** [comment]
Du måste confirma den inom 15 min. Du borde inte lämna datorn heller för att kunna resarvera tiden innan någon annan gör de
et.

**Comment by OscarNaslundCuesta** [comment]
Ja man bör vara tillräckligt nära för att höra. Men reservationen gör väl skripten om jag förstått det rätt? Sedan har man 15 min på sig att confirma.

**Comment by Knaspersky** [comment]
Det värkar inte som om den automatiska reservationen fungerade för mig eller så var det bara att jag var snabbare eftersom jag satt och kollade på den hela tiden.

**Comment by Knaspersky** [comment]
Om den stänger ner igen när du hittar en tid så skriv om du använder Windows PowerShell eller vanliga CMD. Det kanske har med saken att göra.

**Comment by OscarNaslundCuesta** [comment]
Jag använder Terminal på Mac (tror det motsvarar CMD)

**Comment by Knaspersky** [comment]
Ja det gör det. Vi får se om Chrome kraschar eller inte.

**Comment by OscarNaslundCuesta** [comment]
Lär nog ta ett tag. Inte många tider för manuell uppkörning i Stockholm (eller någon annan stans för den delen)

**Comment by Knaspersky** [comment]
Märkte det när jag skulle ta screenshoten.

**Comment by Knaspersky** [comment]
Du kan ju testa kolla efter någon tid för kunskapsprov för t. ex. AM genom att resarvera en tid och sen avbryta den för att se om det kraschar.

**Comment by OscarNaslundCuesta** [comment]
Har du konfigurerat den 
![Skärmavbild 2021-04-07 kl  19 56 34](https://user-images.githubusercontent.com/81713281/113912496-79154080-97db-11eb-9ddf-712629341267.png)
såhär?

**Comment by Knaspersky** [comment]
Ungefär, min ser ut så här
![image](https://user-images.githubusercontent.com/53581552/113914257-a82cb180-97dd-11eb-9cf8-e8f3a08216b5.png)

**Comment by Knaspersky** [comment]
Den ser ut så just nu för att jag försöker hitta en tid i Stockholm istället för i Nyköping. Min förra hade andra datum och fler platser.

**Comment by Knaspersky** [comment]
Men din ser bra ut.

**Comment by Knaspersky** [comment]
Jag kom på att det inte spelar någon roll att jag ändrade "rent_option" till nej.

**Comment by OscarNaslundCuesta** [comment]
Kraschar tyvärr fortfarande

**Comment by Knaspersky** [comment]
Har du en windows dator du kan köra via?

**Comment by OscarNaslundCuesta** [comment]
Kan testa. Återkommer om ett tag

**Comment by Knaspersky** [comment]
Låter bra.

**Comment by Knaspersky** [comment]
Hur går det?

**Comment by Zmia206** [comment]
Gick det att fixa? får inte igång den

**Comment by leonardwarner** [comment]
Min lyckas inte välja språk. Men tack vare OscarNaslundCuesta's lösning letar den nu på olika ställen och inte bara på samma.

**Comment by leonardwarner** [comment]
Här är min config om det är interessant.
![image](https://user-images.githubusercontent.com/36009933/127304684-6d71d53e-d5d9-4e8c-b48b-5b1f545a48cf.png)

**Comment by Daky60** [comment]
Detta ska vara löst sedan senaste uppdateringen. Ladda ned alla filer på nytt och testa igen!
