### ISSUE TITLE
Får det inte att fungera

### ISSUE THREAD

**Issue by izzeww** [Daky60/provbokning_trafikverket#3]
Försöker att använda denna för att boka körprov men den vill inte fungera, utan fastnar på stället där den ska skriva in vilket typ av prov det är. 
![image](https://user-images.githubusercontent.com/9016665/117861869-39d28780-b292-11eb-923a-7b4b7b3fe234.png)
![image](https://user-images.githubusercontent.com/9016665/117861954-579fec80-b292-11eb-84c5-5a0e2e68f01c.png)
![image](https://user-images.githubusercontent.com/9016665/117862002-68506280-b292-11eb-9020-10058cb19c1b.png)

**Comment by Zmia206** [comment]
Har du fått den att funka?

**Comment by leonardwarner** [comment]
'Körprov' ska bytas till 'Körprov B'
