### ISSUE TITLE
Byter inte plats?

### ISSUE THREAD

**Issue by Zmia206** [Daky60/provbokning_trafikverket#4]
Så det tog mig tid nog för att få det att funka, men nu så vad jag än skriver i locations så fastnar den på 1 stad. Har testat byta, ladda om allt. Men annars ljud och hitta tid funkar som den ska.

**Comment by Daky60** [comment]
Tja!

Kan du lägga upp din config fil? Inkludera ej personnummer!

**Comment by DasSlow** [comment]
Testa att ändra id-control-searchText till id-control-searchText-1-1 på rad 87 i bot.py filen

**Comment by Daky60** [comment]
Ladda ned alla filer på nytt. Allting bör fungera igen efter senaste uppdateringen
