### ISSUE TITLE
Vill inte välja Kunskapsprov

### ISSUE THREAD

**Issue by Troxip** [Daky60/provbokning_trafikverket#7]
![image](https://user-images.githubusercontent.com/15328581/131695056-4efdbf04-447d-4bfb-98a0-dfc3ba525bf3.png)
Har ändrat det till det här. Men scripten vill inte välja "Kunskapsprov"
Scripted ändrar inte välj alternativet till Kunskapsprov

![image](https://user-images.githubusercontent.com/15328581/131695216-3d93b499-3ecc-407d-91f6-a24089f0e548.png)
Hur kan jag fixa det? eller är det jag som har gjort något fel?

**Comment by Daky60** [comment]
Hej!
Ladda ned senaste versionen av skriptet så bör det fungera för dig. Se även till att ta bort b:et i "exam" då de ändrat på trafikverkets sida och de måste matcha varandra

**Comment by Troxip** [comment]
Nu började den välja kunskapsprov men slutade att välja språk.

Försökte fixa men den gick inte.

Den fre 3 sep. 2021 kl 19:05 skrev Daky ***@***.***>:

**Comment by Troxip** [comment]
Okej, det var inget. Förstog vad jag gjorde fel. )).

Den fre 3 sep. 2021 kl 19:40 skrev Abdurahim <
***@***.***>:
