### ISSUE TITLE
searching but not booking

### ISSUE THREAD

**Issue by nabasg** [Daky60/provbokning_trafikverket#8]
Hi been trying this code as per instructed but it is only automatically searching the test dates and not booking anything. No sound is playing either even if there is a date within my specified time period
have tried both bot.py and botv2.py but same result with them

**Comment by nabasg** [comment]
this is the config i am using
social_security = 'yyyymmddxxxx'
license_type = 'B'
exam = 'Körprov'
rent_or_language = 'Ja, automat'
dates = ['2021-09-09', '2022-02-27']
locations = ['Järfälla', 'Farsta', 'Sollentuna', 'Södertälje', 'Västerås', 'Uppsala', 'Enköping']

**Comment by Daky60** [comment]
Hi, I tried your config with both just now and it worked fine for me, although I noticed the error handling was a bit off, which the latest edition of botv2.py should correct. Make sure you have the latest version of the script. It will do nothing for a little while when a time is found but it will select it eventually. Try with the latest botv2.py and let me know if you get any errors and when, or bot.py again

**Comment by nabasg** [comment]
Now it worked with the bot.py but with botv2.py it search the time and the start ringing after a while but no automatic booking was done though. I had an extended time period to search time just to test this but still need to find time within a much shorter time slot.
![image](https://user-images.githubusercontent.com/90326722/132573054-0cef7fe8-6deb-4011-9265-a46426bd902e.png)
